[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python monitor.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[[build.buildTimeCmds]]
command = "python -m ensurepip --upgrade"

[[build.buildTimeCmds]]
command = "pip install --upgrade pip"