[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 monitor.py"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip && pip install -r requirements.txt"]

[phases.build]
cmds = []

[variables]
PYTHONUNBUFFERED = "1"