[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 monitor.py"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && source /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]